name: Test
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
jobs:
  ubuntu-2110:
    name: "Ubuntu 22.04"
    # nested virtualization is only available on macOS hosts
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: "Cache ~/.vagrant.d/boxes"
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-${{ hashFiles('Vagrantfile*') }}

      - run: vagrant up
