name: Test
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
jobs:
  ubuntu-2110:
    name: "Ubuntu 21.10"
    # nested virtualization is only available on macOS hosts
    runs-on: macos-10.15
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: "Cache ~/.vagrant.d/boxes"
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-${{ hashFiles('Vagrantfile*') }}

      - run: vagrant up
